<?php

namespace SuperCommBundle\Repository;

/**
 * Article
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article extends \Doctrine\ORM\EntityRepository
{
    /*
    public function findByCategory($categoryId){

        $query = $this->createQueryBuilder('a')
            ->innerJoin('a.category', 'c')
            ->addSelect('c')
            ->andWhere('a.id = :id')
            ->setParameter('c', $categoryId)
            ->getQuery()
            ->getResult();

        return $query;

    }
    */
}

