<?php

namespace SuperCommBundle\Repository;

/**
 * Category
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Category extends \Doctrine\ORM\EntityRepository
{
}
