<?php

namespace SuperCommBundle\Repository;

/**
 * Page
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Page extends \Doctrine\ORM\EntityRepository
{
}
