<?php

namespace SuperCommBundle\Repository;

/**
 * Product
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product extends \Doctrine\ORM\EntityRepository
{
}
