<?php

namespace SuperCommBundle\Repository;

/**
 * Prospect
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Prospect extends \Doctrine\ORM\EntityRepository
{
}
