<?php

namespace SuperCommBundle\Repository;

/**
 * Upload
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Upload extends \Doctrine\ORM\EntityRepository
{
}
