imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SuperCommBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating: { engines: ['twig'] }


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: SuperCommBundle\Entity\User
    from_email:
        address: "mathilde.vaal@lapiscine.pro"
        sender_name: "Mathilde Vaal"
    registration:
        form:
            type: SuperCommBundle\Form\UserType

easy_admin:
    site_name: 'Admin SuperComm'
    design:
        brand_color: '#00a8b2'
        assets:
            favicon: 'assets/images/favicons/favicon.png'
    list:
        actions: ['show']
        max_results: 15
    entities:
        Article:
            class: SuperCommBundle\Entity\Article
            label: 'Articles'
            list:
                title: 'Articles du blog'
                fields:
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'dateOnPublished', label: 'Date' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'category', label: 'Catégorie(s)' }
                    - { property: 'user', label: 'Expert'}
            form:
                title: "Modifier l'article"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'dateOnPublished', label: 'Date' }
                    - { type: 'divider' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu', type: 'ckeditor' }
                    - { type: 'divider' }
                    - { property: 'category', label: 'Catégorie(s)' }
                    - { property: 'user', label: 'Expert'}
            show:
                title: 'Article'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'dateOnPublished', label: 'Date' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'category', label: 'Catégorie(s)' }
                    - { property: 'user', label: 'Expert'}
        User:
            class: SuperCommBundle\Entity\User
            label: 'Utilisateurs'
            list:
                title: 'Utilisateurs et Administrateurs'
                fields:
                    - id
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'status', label: 'Vous êtes ?' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'enabled', label: 'Autorisé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: "Types d'utilisateurs" }
                    - { property: 'article', label: 'Article' }
                    - { property: 'product', label: 'Produit' }
            form:
                title: "Modifier les données de l'utilisateur"
                fields:
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'status', label: 'Vous êtes ?' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'enabled', label: 'Autorisé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: "Types d'utilisateurs" }
                    - { property: 'article', label: 'Article' }
                    - { property: 'product', label: 'Produit' }
            show:
                title: 'Utilisateur'
                fields:
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'status', label: 'Vous êtes ?' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'enabled', label: 'Autorisé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: "Types d'utilisateurs" }
                    - { property: 'article', label: 'Article' }
                    - { property: 'product', label: 'Produit' }

        Product:
            class: SuperCommBundle\Entity\Product
            label: 'Produits'
            list:
                title: 'Services proposés et/ou packagés'
                fields:
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'user', label: 'SuperAdmin' }
            form:
                title: 'Modifier le produit'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu', type: 'ckeditor' }
                    - { type: 'divider' }
                    - { property: 'user', label: 'SuperAdmin' }
            show:
                title: 'Produit'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'content', label: 'Contenu' }


        Category:
            class: SuperCommBundle\Entity\Category
            label: 'Catégories des articles'
            list:
                title: 'Catégories dans lesquelles classer les articles'
                fields:
                    - id
                    - { property: 'label', label: 'Intitulé' }
            form:
                title: "Modifier la catégorie d'articles"
                fields:
                    - { property: 'label', label: 'Intitulé' }
            show:
                title: 'Catégorie'
                fields:
                    - { property: 'label', label: 'Intitulé' }



ivory_ck_editor:
    default_config: 'my_custom_config'
    configs:
        my_custom_config:
            uiColor: '#00a8b2'
            toolbar: full
            height: '500px'
            language: fr