super_comm_homepage:
    path:     /
    defaults: { _controller: SuperCommBundle:Default:index }

super_comm_conseilMinute:
    path:     /conseil-a-la-minute
    defaults: { _controller: SuperCommBundle:Default:conseilMinute }

super_comm_offres:
    path:     /nos-offres
    defaults: { _controller: SuperCommBundle:Default:offres }

super_comm_experts:
    path:     /nos-experts
    defaults: { _controller: SuperCommBundle:Default:experts }

super_comm_blog:
    path:     /vos-outils-web-marketing
    defaults: { _controller: SuperCommBundle:Default:blog }

super_comm_ressources:
    path:     /vos-outils-web-marketing/{categorie}
    defaults: { _controller: SuperCommBundle:Default:ressources }

super_comm_ressource_detail:
    path:     /vos-outils-web-marketing/{categorie}/{article}
    defaults: { _controller: SuperCommBundle:Default:ressourceDetail }

super_comm_inscription:
    path:     /inscription
    defaults: { _controller: SuperCommBundle:Default:inscription }

super_comm_mentions_legales:
    path:     /mentions-legales
    defaults: { _controller: SuperCommBundle:Default:mentionsLegales }
